# Generated by Django 2.1.4 on 2019-01-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_transaction'),
        ('shop', '0008_transaction'),
    ]

    operations = [
    ]
